version: "3.8"

services:
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - "./docker/php/php.ini-development:/usr/local/etc/php/php.ini"
      - "./src:/var/www/html"
      - "./docker/logs/php:/var/log/php"

  nginx:
    build:
      context: ./docker/nginx
      args:
        - DEV_DOMAIN=${DEV_DOMAIN}
    container_name: nginx
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/var/www/html"
      - "./docker/logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on:
      - php

  mysql:
    build:
      context: ./docker/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db-store:/var/lib/mysql"
      - "./docker/logs/mysql:/var/log/mysql"
      - "./docker/mysql/initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  db-store:
